spring:
  ai:
    mcp:
      client:
        enabled: true
        name: spring-ai-demo-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC  # 使用异步模式支持响应式
        sse:
          connections:
            server1:
              url: http://127.0.0.1:8080
        toolcallback:
          enabled: true
        health-check:
          enabled: true
          interval: 30s
          timeout: 5s
        retry:
          max-attempts: 3
          backoff-interval: 60s